import { Plus_Jakarta_Sans } from 'next/font/google'
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-jakarta',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${plusJakartaSans.variable} `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
